<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCNuAUpF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__ . '/ContainerCNuAUpF/App_KernelDevDebugContainer.php') {
    touch(__DIR__ . '/ContainerCNuAUpF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCNuAUpF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCNuAUpF\App_KernelDevDebugContainer([
    'container.build_hash' => 'CNuAUpF',
    'container.build_id' => '7a93521e',
    'container.build_time' => 1642140899,
], __DIR__ . \DIRECTORY_SEPARATOR . 'ContainerCNuAUpF');
