<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ6Dcqwc\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ6Dcqwc/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerZ6Dcqwc.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerZ6Dcqwc\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerZ6Dcqwc\App_KernelProdContainer([
    'container.build_hash' => 'Z6Dcqwc',
    'container.build_id' => '09331d46',
    'container.build_time' => 1646138397,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ6Dcqwc');
