<?php

namespace ContainerLxlIlLB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wk3xYgrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Wk3xYgr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Wk3xYgr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'url' => ['privates', '.errored..service_locator.Wk3xYgr.App\\Entity\\UrlAdress', NULL, 'Cannot autowire service ".service_locator.Wk3xYgr": it references class "App\\Entity\\UrlAdress" but no such service exists.'],
        ], [
            'manager' => '?',
            'url' => 'App\\Entity\\UrlAdress',
        ]);
    }
}
