<?php

namespace ContainerLxlIlLB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUrlAdressService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Wk3xYgr.App\Entity\UrlAdress' shared service.
     *
     * @return \App\Entity\UrlAdress
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Wk3xYgr": it references class "App\\Entity\\UrlAdress" but no such service exists.');
    }
}
