<?php

namespace Container1jNKXGj;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoom2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kmeuOUR.App\Entity\Room' shared service.
     *
     * @return \App\Entity\Room
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.kmeuOUR": it references class "App\\Entity\\Room" but no such service exists.');
    }
}
