<?php

namespace Container1jNKXGj;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoomFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\RoomFormType' shared autowired service.
     *
     * @return \App\Form\RoomFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4) . '' . \DIRECTORY_SEPARATOR . 'vendor' . \DIRECTORY_SEPARATOR . 'symfony' . \DIRECTORY_SEPARATOR . 'form' . \DIRECTORY_SEPARATOR . 'FormTypeInterface.php';
        include_once \dirname(__DIR__, 4) . '' . \DIRECTORY_SEPARATOR . 'vendor' . \DIRECTORY_SEPARATOR . 'symfony' . \DIRECTORY_SEPARATOR . 'form' . \DIRECTORY_SEPARATOR . 'AbstractType.php';
        include_once \dirname(__DIR__, 4) . '' . \DIRECTORY_SEPARATOR . 'src' . \DIRECTORY_SEPARATOR . 'Form' . \DIRECTORY_SEPARATOR . 'RoomFormType.php';

        return $container->privates['App\\Form\\RoomFormType'] = new \App\Form\RoomFormType();
    }
}
