<?php

namespace ContainerZ6Dcqwc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JWC0iAMService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.jWC0iAM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jWC0iAM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'flash' => ['privates', 'session.flash_bag', 'getSession_FlashBagService', true],
            'userPasswordHasherInterface' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'flash' => '?',
            'userPasswordHasherInterface' => '?',
        ]);
    }
}
