<?php

namespace ContainerZ6Dcqwc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoom2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.kmeuOUR.App\Entity\Room' shared service.
     *
     * @return \App\Entity\Room
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.kmeuOUR": it references class "App\\Entity\\Room" but no such service exists.');
    }
}
