<?php

namespace ContainerZ6Dcqwc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoomControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Room\RoomController' shared autowired service.
     *
     * @return \App\Controller\Room\RoomController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Room\\RoomController'] = $instance = new \App\Controller\Room\RoomController();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\Room\\RoomController', $container));

        return $instance;
    }
}
