<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB5VQyHt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB5VQyHt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB5VQyHt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB5VQyHt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB5VQyHt\App_KernelDevDebugContainer([
    'container.build_hash' => 'B5VQyHt',
    'container.build_id' => 'fdc93e72',
    'container.build_time' => 1646642163,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB5VQyHt');
